{% set name = "synced_collections" %}
{% set version = "1.0.0" %}
{% set sha256 = "b770a99c8455cb00dce4645525f8092f4ec15a9d028276777f266f9652f6b8f5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/glotzerlab/synced_collections/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - synced_collections
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://signac.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Interact with persistent key-value stores using Pythonic abstractions.
  description: |
    The synced_collections package provides Pythonic abstractions over various
    underlying data stores, presenting APIs that behave like standard built-in
    Python collections like dicts. synced_collections can synchronize with a range
    of data stores, including MongoDB databases and Zarr groups.
  doc_url: https://docs.signac.io
  dev_url: https://github.com/glotzerlab/synced_collections

extra:
  recipe-maintainers:
    - cbkerr
    - b-butler
    - bdice
    - vyasr
    - mikemhenry
